addSbtPlugin("io.spray"               %  "sbt-revolver"          % "0.9.1")
addSbtPlugin("com.typesafe.sbt"       %  "sbt-native-packager"   % "1.3.12")
addSbtPlugin("net.virtual-void"       %  "sbt-dependency-graph"  % "0.9.2")
addSbtPlugin("com.timushev.sbt"       %  "sbt-updates"           % "0.3.4")
addSbtPlugin("io.get-coursier"        %  "sbt-coursier"          % "1.0.3")